server {
    listen 8080; # Super bien por el usuario no root
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # El slash al final de la IP evita errores de rutas 404 en el backend
        proxy_pass http://10.0.2.115:3001/;   

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Despertando a GitHub frontend