version: '3.8'

services:
  # ==========================================
  # 1. Base de Datos (Instancia: DATA)
  # ==========================================
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: tienda-db
    restart: always
    # Mapeamos 3306:3306 para que sea estándar y fácil de conectar
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - innovatech_net

  # ==========================================
  # 2. Backend (Instancia: BACKEND)
  # ==========================================
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tienda-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      # CAMBIO CLAVE: Aquí usamos la IP Privada de la instancia de DATA
      # para que el Back encuentre la base de datos en AWS
      DB_HOST: 10.0.2.134  
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_perritos
      DB_PORT: 3306
    networks:
      - innovatech_net

  # ==========================================
  # 3. Frontend (Instancia: FRONTEND)
  # ==========================================
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tienda-frontend
    restart: always
    # Cumplimos con usuario NO ROOT: Nginx corre en 8080 y lo sacamos por el 80
    ports:
      - "80:8080"
    networks:
      - innovatech_net

# ==========================================
# Redes y Volúmenes (Persistencia y Aislamiento)
# ==========================================
networks:
  innovatech_net:
    driver: bridge

volumes:
  db_data:
    # Esto asegura que los perritos no se borren si reinicias el contenedor